#+TITLE: RPGGame

This Document generated by:
https://github-com.translate.goog/kenjirofukuda/gnustep-examples/blob/main/RPGGame/README_ja.org?_x_tr_sl=ja&_x_tr_tl=en&_x_tr_hl=ja&_x_tr_pto=wapp

* Overview
This application was implemented in GNUstep (Objective-C) following RyiSnow's playlist.

- Playlist :: [[https://www.youtube.com/playlist?list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq][How to Make a 2D Game in Java ]]

All images and audio in the Resources/ folder are made publicly available by RyiSnow.

* What's great about RyiSnow
- He refrains from selling himself (showing his face) and focuses on explaining things.
- Do not hide any mistakes (encourage viewers to notice them)
- By avoiding the optimization that advanced users often do and instead coding steadily, beginners are not left behind.
- Despite having the skill, he chooses to hold it back.
- They accept suggestions in the comments section and respond to all error reports from beginners.
- Rather than relying on the theories that are all over the place, we teach the joy of thinking for oneself and devising new ideas.

I could never imitate him. He is a man of great character.

* Main differences with Java
** Coordinate system
In a typical device coordinate system, the increasing direction of Y is downwards, but NSView defines the increasing direction of Y, which is closer to the real world Postscript system, as upwards. Therefore, the numerical representation of ROW is upside down.

Originally, we supported the flip coordinate system, but we stopped using it and marked it as deprecated.

* Animation Differences
I don't understand how to use NSAnimation, so I'm using NSTimer.

The course includes various measures to achieve accurate FPS, but I compromised in this area and cut corners.

* Differences from Apple Cocoa

GNUstep has announced that its API level is quite close to Apple's, but this is only for Foundation.
AppKit is not implemented. Or, even if there is an API in the header,
it is an empty implementation, or it is full of TODO and FIXME and has not been boiled down.
Therefore, it relies on a fairly old API that Apple has treated as deprecated a long time ago.

I don't have the equipment to run Cocoa, so I don't support Apple.

* Notes
** Renaissance
GUI resources are defined using Renaissance.

The original Renaissance has not been maintained for a long time and does not work properly. Therefore, when using it ,
please use the repository https://github.com/kenjirofukuda/libs-renaissance.git which has been cloned and modified .

I'm not familiar with git, so I haven't made any pull requests to upstream.

** compiler
Requires clang and libobjc2.

Since it uses some features of Objective-C 2.0, it does not support gobjc.

Memory management basically makes extensive use of GNUstep macros to minimize modifications when compiling with ARC.

Some blocks are used.

** Coding style
Currently we use the GNU style, but this may change in the future.

Properties have not yet been actively adopted, and we still use the traditional redundant setter/getter methods.

I don't like the dot notation for property expressions.
I'm avoiding this confusing notation to be aware of the difference with structures (for now).

* Progress
- [X] #1 [[https://www.youtube.com/watch?v=om59cwR7psI&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=1&t=14s&pp=iAQB][The MechaniThe Mechanism of 2D Games]]
- [X] #2 [[https://www.youtube.com/watch?v=VpH33Uw-_0E&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=2&t=1674s&pp=iAQB][Game Loop and Key Input]]
- [X] #3 [[https://www.youtube.com/watch?v=wT9uNGzMEM4&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=3&t=2s&pp=iAQB][Sprites and Animation]]
- [X] #4 [[https://www.youtube.com/watch?v=ugzxCcpoSdE&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=5&t=1357s&pp=iAQB][Drawing Tiles]]
- [X] #5 [[https://www.youtube.com/watch?v=Ny_YHoTYcxo&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=6&t=1271s&pp=iAQB][World and Camera]]
- [X] #6 [[https://www.youtube.com/watch?v=oPzPpUcDiYY&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=7&t=734s&pp=iAQB][Collision Detection]]
- [X] #7 [[https://www.youtube.com/watch?v=xYtXz34IJdY&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=8&t=14s&pp=iAQB][Object Placement]]
- [X] #8 [[https://www.youtube.com/watch?v=srvDSypsJL0&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=9&t=7s&pp=iAQB][Object Interaction]]
- [X] #9 [[https://www.youtube.com/watch?v=nUHh_J2Acy8&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=10&t=7s&pp=iAQB][Sound]]
- [X] #10 [[https://www.youtube.com/watch?v=0yD5iT8ObCs&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=11&t=286s&pp=iAQB][The First Game Done (UI)]]
- [ ] #11 [[https://www.youtube.com/watch?v=fZLfJSXs0BU&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=13&t=83s&pp=iAQB][Improving Rendering Performance]]
...
- [ ] #56 [[https://www.youtube.com/watch?v=9czCgoBstn8&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=62&pp=iAQB][Cutscene]]
- [ ] #Final [[https://www.youtube.com/watch?v=9jjWFjGAjRM&list=PL_QPQmz5C6WUF-pOQDsbsKbaBZqXj4qSq&index=63&pp=iAQB][Ending]]

